### ISSUE TITLE
Initial multilingual translation

### ISSUE THREAD

**Issue by volloholic** [africanmathsinitiative/R-Instat#3721]
Establishment of the multi lingual functionality and translation into at least one other language. (Probably French)

**Comment by Ogik99** [comment]
#4176 
#5096

**Comment by dannyparsons** [comment]
We have now decided on the approach as suggested also for Climsoft here https://github.com/opencdms/Climsoft/issues/200#issuecomment-474824472.
This will be simpler to implement in Climsoft and so will be implemented there first before being used in R-Instat.

**Comment by isedwards** [comment]
@dannyparsons - There are three commits in the [Climsoft/#592](https://github.com/climsoft/Climsoft/pull/592/commits) pull request for adding language translation.

- [bb1d840](https://github.com/climsoft/Climsoft/pull/592/commits/bb1d84071d95a9290629a4d499b083b3a2eddfd3) adds the command `SimpleTranslateTool.translateForm(Me)` to every form. You can ignore this commit. Hopefully in R-Instat all forms may inherit from a single parent base form, in which case you would only have to add this command in one place and all forms would then inherit the code.
- [7f3a803](https://github.com/climsoft/Climsoft/pull/592/commits/7f3a803790faba850b1175e0f6c75d01c22c389b) can also be ignored. It adds the binary SQLite file that contains translations for the Climsoft interface. R-Instat will need an equivalent file.
- [93f2ea7](https://github.com/climsoft/Climsoft/pull/592/commits/93f2ea7ad4f5ab67ac5b4bb94f608072a3490e7a) this commit contains [clsSimpleTranslateTool.vb ](https://github.com/climsoft/Climsoft/blob/93f2ea7ad4f5ab67ac5b4bb94f608072a3490e7a/ClimsoftVer4/ClimsoftVer4/clsSimpleTranslateTool.vb). You should be able to reuse some of this code. The majority of other changes in this commit are removing an older attempt at language translation from Climsoft (some of which is just hardcoded).


There are currently three known problems with [clsSimpleTranslateTool.vb ](https://github.com/climsoft/Climsoft/blob/93f2ea7ad4f5ab67ac5b4bb94f608072a3490e7a/ClimsoftVer4/ClimsoftVer4/clsSimpleTranslateTool.vb).

The first is that it used to use RESX files instead of a local SQLite database. RESX files are very limited - there is only one key and one value, therefore the implementation didn't use multiple columns for `language_code`, `form_name` etc. Instead the variables were combined into the RESX's single key using two underscores. E.g. `en__mainform__titlecontrol__...`.

This led to obscure code like...
```
startswith = String.Format("{0}\_\_{1}\_\_", languageCode, frm.Name)
```

In SQLite it would be much better to implement this as:

| language_code | form_name | control_name | original_text | translation            |
|------------------|--------------|----------------|---------------|---------------------|
| fr                       | mainform    | lblTitle           | Hello World  | Bonjour le monde | 
| ...                       | ...                 | ...                    | ...                  | ...                            |

The other two problems are mentioned in [Climsoft/#592](https://github.com/climsoft/Climsoft/pull/592):

> currently exceptions are raised and caught when controls are not found and also only static strings (that are defined at design time) are being translated

The easiest approach would probable be to rewrite language translation from scratch using [clsSimpleTranslateTool.vb ](https://github.com/climsoft/Climsoft/blob/93f2ea7ad4f5ab67ac5b4bb94f608072a3490e7a/ClimsoftVer4/ClimsoftVer4/clsSimpleTranslateTool.vb) as a guide. Feel free to copy and paste any of the code that you need.

**Comment by lloyddewit** [comment]
@maxwellfundi I will work on this issue

**Comment by rdstern** [comment]
I query whether tooltips will be translated?  If this is not possible initially, might it be possible in the future?

They can be useful in some dialogues and menu items.  If they are translated, with the current system of producing them, then I suggest this could warrant putting more effort into producing them in more of the software.

If this is not possible in the current "system", then I wonder if it may be possible to change the way tooltips are coded, to facilitate the possibility of translation?

**Comment by lloyddewit** [comment]
@rdstern Thank you for the suggestion. I will try and translate tool tips. I am implementing translations in the order of priority below. If you prefer a different priority, then let me know, thanks

- frmMain menu items
- frmMain other controls (e.g. split window titles)
- dialogs: controls with static text
- dialogs: dynamic switching between translation and English
- message boxes (e.g. startup and developer errors)
- tool tips
- dialogs: controls that have dynamically changing text

**Comment by rdstern** [comment]
@lloyddewit that sounds fine.  And I assume this answers my main question, namely that sometime in the future tooltips will be included.  

Hence, not for the sprint, but this means I should soon work with the documentation team on adding more tooltips to the software.  Exciting!

**Comment by dannyparsons** [comment]
Tooltips are just controls in VB like everything else so no reason they won't be included in the system.

**Comment by lloyddewit** [comment]
This PR is partially resolved in PR #6413 .

Here is a list of translation cases that still need to be implemented:
- **Controls with the same name in the same form/dialog/subdialog**. In most cases, this can be resolved by changing the name of the controls to make them unique. However, there are some cases where this is not possible. An example is in `sdgLayerOptions`. This subdialog contains 2 `ucrGeom` objects, which both have a  `lblTypeofLayer` control. Only one of these is translated in the current translation mechanism. In order to translate both labels, we would need a way to uniquely identify and store each label. This could be done by adding an extra column to form_controls to identify the panel that contains each label. Or we could dynamically give each label a unique name during the translation (`lblTypeofLayer1`, `lblTypeofLayer2` etc.).

**Comment by lloyddewit** [comment]
> 
>     * **Controls with the same name in the same form/dialog/subdialog**. In most cases, this can be resolved by changing the name of the controls to make them unique. However, there are some cases where this is not possible. An example is in `sdgLayerOptions`. This subdialog contains 2 `ucrGeom` objects, which both have a  `lblTypeofLayer` control. Only one of these is translated in the current translation mechanism. In order to translate both labels, we would need a way to uniquely identify and store each label. This could be done by adding an extra column to form_controls to identify the panel that contains each label. Or we could dynamically give each label a unique name during the translation (`lblTypeofLayer1`, `lblTypeofLayer2` etc.). The screenshots below show another example.

The above issue is fixed in PR #6469

**Comment by lloyddewit** [comment]
Here is a list of translation cases that still need to be implemented (in priority order):

- [ ] drop-down lists
- [ ] tool tips
- [ ] tag controls to explicitly prevent their text from being translated. For example, if a control's text represents the name of an R parameter, then this text should not be translated.
- [ ] message boxes (e.g. startup and developer errors)
- [ ] text constructed from separate elements (e.g. 'row 3 of 5')
- [ ] text containing carriage returns or line feeds (causes problems for the csv files that I use to populate the database)
    text containing special characters like ''. (Note: single quotes are already handled, other special characters are not yet tested, they may not cause issues for R-Instat; we shoud also test any potential impact on the JSON files used by CrowdIn)

**Comment by lloyddewit** [comment]
Here is a list of translation mechanism features that still need to be implemented (in priority order):

- [ ] translate drop-down lists
- [ ] translate tool tips
- [ ] tag controls to explicitly prevent their text from being translated. For example, if a control's text represents the name of an R parameter, then this text should not be translated.
- [ ] translate message boxes (e.g. startup and developer errors)
- [ ] translate text constructed from separate elements (e.g. 'row 3 of 5')
- [ ] translate text containing carriage returns or line feeds (causes problems for the csv files that I use to populate the database)
- [ ] translate text containing special characters like '"' (double quote). (Note: single quotes are already handled, other special characters are not yet tested, they may not cause issues for R-Instat; we shoud also test any potential impact on the JSON files used by CrowdIn)

**Comment by lloyddewit** [comment]
Accidentally closed by PR #6621

**Comment by rdstern** [comment]
@lloyddewit I wonder about the situation regarding tooltips.  For example the Prepare > Calculator dialogue has quite a lot of them?  Are they done dialogue-by-dialogue or more generally?

**Comment by lloyddewit** [comment]
> @lloyddewit I wonder about the situation regarding tooltips. For example the Prepare > Calculator dialogue has quite a lot of them? Are they done dialogue-by-dialogue or more generally?

The tooltip translation mechanism is in place and working. However each time a tooltip is updated/added it needs to go through the standard JSON/CrowdIn/database process. I will try and regenerate the list of all tooltip text, and add any missing tooltip text to the JSON file for translation. This should solve the issue for most tooltips. If there are any tooltips still not translating, then we'll need to address these separately.
