### ISSUE TITLE
Summary of remaining translation mechanism issues

### ISSUE THREAD

**Issue by lloyddewit** [africanmathsinitiative/R-Instat#8323]
This issue replaces issue #3721.
Here is a list of translation mechanism features that still need to be implemented (in priority order):

- [ ] translate message boxes (e.g. startup and developer errors). See issue #7774 for examples.
- [ ] translate drop-down lists. See PR #8319 for an example list of colours.
- [ ] translate right click selector menus (see issue #8196 for example)
- [ ] translate text constructed from separate elements (e.g. 'row 3 of 5'). A specific instance of this issue is described in issue #6563.
- [ ] translate text containing carriage returns or line feeds (causes problems for the csv files that I use to populate the database)
- [ ] translate text containing special characters like '"' (double quote). (Note: single quotes are already handled, other special characters are not yet tested, they may not cause issues for R-Instat; we should also test any potential impact on the JSON files used by CrowdIn)
- [ ] translate headings in selectors (see screenshot 1 below for example of untranslated selector heading text)

Screenshot 1:

![image](https://user-images.githubusercontent.com/57253949/182827101-e2593125-db74-4343-a06a-5063da3abfea.png)
